### ISSUE TITLE
Slower-Header-Animations

### ISSUE THREAD

**Issue by eyyMinda** [student-to-dev/Omex-landing-page#61]
- Add transition durations to all of header animations (link drop downs)

- Return animation after moving cursor away

- cursor: pointer on burger icon

- After opening a drop down menu and having another drop down menu opened inside it, there is a gap between them. Increase padding just enough for you not to close it by accidently hovering in between them.
(Example: open "Pages", open "Case Study")

- On mobile: After opening drop down menu and having another drop down menu opened inside it, contents in the second one are all highlighted red. Should be one by one after hovering on them.
(Example: open "Pages", open "eCommerence"

**Comment by agnekauk** [comment]
Could @eyyMinda please specify this: Return animation after moving cursor away?

**Comment by eyyMinda** [comment]
> Could @eyyMinda please specify this: Return animation after moving cursor away?

onHover: executes animation. But onMouseOut instant scale/transform return to default position. There is no animation for moving cursor away.

Example for fix:

While having this for animation.
`.aLink:hover { transform: translateX(5px); transition: transform 1s; }`


Add this for it to return to default with animation also.
`.aLink { transform: translateX(0px); transition: transform 1s; }`
